version: 4
# Home Assistant integration (MQTT discovery)
homeassistant:
    enabled: false

# Enable the frontend, runs on port 8080 by default
frontend:
    enabled: true
    port: 8888

# Advanced settings
advanced:
    channel: 11
    # Let Zigbee2MQTT generate a network key on first start
    network_key: GENERATE
    # Let Zigbee2MQTT generate a pan_id on first start
    pan_id: GENERATE
    # Let Zigbee2MQTT generate a ext_pan_id on first start
    ext_pan_id: GENERATE